// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.ProjectManagement.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.ProjectManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectManagementDbContext))]
    [Migration("20260715003053_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("projectmanagement")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.ProjectManagement.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_number");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("ExtensionFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extension_data");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("project_name");

                    b.Property<string>("ProjectNameArabic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("project_name_arabic");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("projects", "projectmanagement");
                });

            modelBuilder.Entity("Modules.ProjectManagement.Domain.WbsElement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsAccountAssignmentElement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_account_assignment_element");

                    b.Property<bool>("IsBillingElement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_billing_element");

                    b.Property<bool>("IsPlanningElement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_planning_element");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameArabic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_arabic");

                    b.Property<Guid?>("ParentWbsElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_wbs_element_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("wbs_elements", "projectmanagement");
                });

            modelBuilder.Entity("Modules.ProjectManagement.Infrastructure.NumberRangeCounterEntity", b =>
                {
                    b.Property<string>("RangeKey")
                        .HasColumnType("text")
                        .HasColumnName("range_key");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence");

                    b.HasKey("RangeKey", "CompanyId", "FiscalYear");

                    b.ToTable("number_range_counters", "projectmanagement");
                });

            modelBuilder.Entity("Platform.Workflow.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicableSteps")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("applicable_steps");

                    b.Property<Guid>("BusinessObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_id");

                    b.Property<string>("BusinessObjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("business_object_type");

                    b.Property<int>("CurrentStepIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_step_index");

                    b.Property<DateTimeOffset?>("CurrentStepStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_step_started_at");

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("definition_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("_approvedByStep")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("approved_by_step");

                    b.Property<string>("_history")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("history");

                    b.Property<string>("_requiredApproversByStep")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("required_approvers_by_step");

                    b.HasKey("Id");

                    b.ToTable("workflow_instances", "projectmanagement");
                });

            modelBuilder.Entity("Modules.ProjectManagement.Domain.WbsElement", b =>
                {
                    b.HasOne("Modules.ProjectManagement.Domain.Project", null)
                        .WithMany("WbsElements")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.ProjectManagement.Domain.Project", b =>
                {
                    b.Navigation("WbsElements");
                });
#pragma warning restore 612, 618
        }
    }
}
