// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.MasterData.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.MasterData.Infrastructure.Migrations
{
    [DbContext(typeof(MasterDataDbContext))]
    [Migration("20260714152130_AddCostCenter")]
    partial class AddCostCenter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("masterdata")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.MasterData.Domain.BusinessPartner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_number");

                    b.Property<string>("ExtensionFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extension_data");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameArabic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_arabic");

                    b.Property<string>("PartnerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("partner_type");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TaxRegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_registration_number");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("business_partners", "masterdata");
                });

            modelBuilder.Entity("Modules.MasterData.Domain.BusinessPartnerAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address_line");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("address_type");

                    b.Property<Guid>("BusinessPartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_partner_id");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.HasKey("Id");

                    b.HasIndex("BusinessPartnerId");

                    b.ToTable("business_partner_addresses", "masterdata");
                });

            modelBuilder.Entity("Modules.MasterData.Domain.BusinessPartnerContact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessPartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_partner_id");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("job_title");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessPartnerId");

                    b.ToTable("business_partner_contacts", "masterdata");
                });

            modelBuilder.Entity("Modules.MasterData.Domain.CostCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CostCenterCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cost_center_code");

                    b.Property<string>("CostCenterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cost_center_name");

                    b.Property<string>("CostCenterNameArabic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cost_center_name_arabic");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_number");

                    b.Property<string>("ExtensionFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extension_data");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPostable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_postable");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<Guid?>("ParentCostCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_cost_center_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CostCenterCode")
                        .IsUnique();

                    b.HasIndex("ParentCostCenterId");

                    b.ToTable("cost_centers", "masterdata");
                });

            modelBuilder.Entity("Modules.MasterData.Domain.GLAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_code");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountNameArabic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("account_name_arabic");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_number");

                    b.Property<string>("ExtensionFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extension_data");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPostable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_postable");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<Guid?>("ParentAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_account_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AccountCode")
                        .IsUnique();

                    b.HasIndex("ParentAccountId");

                    b.ToTable("gl_accounts", "masterdata");
                });

            modelBuilder.Entity("Modules.MasterData.Domain.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_number");

                    b.Property<string>("ExtensionFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extension_data");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_code");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("item_name");

                    b.Property<string>("ItemNameArabic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("item_name_arabic");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("item_type");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit_of_measure");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.ToTable("items", "masterdata");
                });

            modelBuilder.Entity("Modules.MasterData.Infrastructure.AttachmentContentRow", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.HasKey("AttachmentId");

                    b.ToTable("attachment_contents", "masterdata");
                });

            modelBuilder.Entity("Modules.MasterData.Infrastructure.NumberRangeCounterEntity", b =>
                {
                    b.Property<string>("RangeKey")
                        .HasColumnType("text")
                        .HasColumnName("range_key");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence");

                    b.HasKey("RangeKey", "CompanyId", "FiscalYear");

                    b.ToTable("number_range_counters", "masterdata");
                });

            modelBuilder.Entity("Platform.Attachments.AttachmentMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_id");

                    b.Property<string>("BusinessObjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("business_object_type");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("BusinessObjectType", "BusinessObjectId");

                    b.ToTable("attachments", "masterdata");
                });

            modelBuilder.Entity("Platform.Notes.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_id");

                    b.Property<string>("BusinessObjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("business_object_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessObjectType", "BusinessObjectId");

                    b.ToTable("notes", "masterdata");
                });

            modelBuilder.Entity("Platform.Workflow.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicableSteps")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("applicable_steps");

                    b.Property<Guid>("BusinessObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_id");

                    b.Property<string>("BusinessObjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("business_object_type");

                    b.Property<int>("CurrentStepIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_step_index");

                    b.Property<DateTimeOffset?>("CurrentStepStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_step_started_at");

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("definition_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("_approvedByStep")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("approved_by_step");

                    b.Property<string>("_history")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("history");

                    b.Property<string>("_requiredApproversByStep")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("required_approvers_by_step");

                    b.HasKey("Id");

                    b.ToTable("workflow_instances", "masterdata");
                });

            modelBuilder.Entity("Modules.MasterData.Domain.BusinessPartnerAddress", b =>
                {
                    b.HasOne("Modules.MasterData.Domain.BusinessPartner", null)
                        .WithMany("Addresses")
                        .HasForeignKey("BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.MasterData.Domain.BusinessPartnerContact", b =>
                {
                    b.HasOne("Modules.MasterData.Domain.BusinessPartner", null)
                        .WithMany("Contacts")
                        .HasForeignKey("BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.MasterData.Domain.CostCenter", b =>
                {
                    b.HasOne("Modules.MasterData.Domain.CostCenter", null)
                        .WithMany()
                        .HasForeignKey("ParentCostCenterId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Modules.MasterData.Domain.GLAccount", b =>
                {
                    b.HasOne("Modules.MasterData.Domain.GLAccount", null)
                        .WithMany()
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Modules.MasterData.Infrastructure.AttachmentContentRow", b =>
                {
                    b.HasOne("Platform.Attachments.AttachmentMetadata", null)
                        .WithOne()
                        .HasForeignKey("Modules.MasterData.Infrastructure.AttachmentContentRow", "AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.MasterData.Domain.BusinessPartner", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
