// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Procurement.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Procurement.Infrastructure.Migrations
{
    [DbContext(typeof(ProcurementDbContext))]
    [Migration("20260714230934_AddGoodsReceiptNote")]
    partial class AddGoodsReceiptNote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("procurement")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Procurement.Domain.GoodsReceiptNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_number");

                    b.Property<string>("ExtensionFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extension_data");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_id");

                    b.Property<DateOnly>("ReceivedDate")
                        .HasColumnType("date")
                        .HasColumnName("received_date");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("goods_receipt_notes", "procurement");
                });

            modelBuilder.Entity("Modules.Procurement.Domain.GrnLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GoodsReceiptNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("goods_receipt_note_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("PurchaseOrderLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_line_id");

                    b.Property<decimal>("QuantityReceived")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity_received");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("GoodsReceiptNoteId");

                    b.ToTable("grn_lines", "procurement");
                });

            modelBuilder.Entity("Modules.Procurement.Domain.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_number");

                    b.Property<string>("ExtensionFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extension_data");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<Guid?>("RequestForQuotationId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_for_quotation_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("purchase_orders", "procurement");
                });

            modelBuilder.Entity("Modules.Procurement.Domain.PurchaseOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CostCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cost_center_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("RfqLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("rfq_line_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("purchase_order_lines", "procurement");
                });

            modelBuilder.Entity("Modules.Procurement.Domain.PurchaseRequisition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_number");

                    b.Property<string>("ExtensionFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extension_data");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<DateOnly?>("RequiredByDate")
                        .HasColumnType("date")
                        .HasColumnName("required_by_date");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("purchase_requisitions", "procurement");
                });

            modelBuilder.Entity("Modules.Procurement.Domain.PurchaseRequisitionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CostCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cost_center_id");

                    b.Property<decimal>("EstimatedUnitPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("estimated_unit_price");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("LineDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("line_description");

                    b.Property<Guid>("PurchaseRequisitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_requisition_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseRequisitionId");

                    b.ToTable("purchase_requisition_lines", "procurement");
                });

            modelBuilder.Entity("Modules.Procurement.Domain.RequestForQuotation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_number");

                    b.Property<string>("ExtensionFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extension_data");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("PurchaseRequisitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_requisition_id");

                    b.Property<DateOnly?>("ResponseDeadline")
                        .HasColumnType("date")
                        .HasColumnName("response_deadline");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("requests_for_quotation", "procurement");
                });

            modelBuilder.Entity("Modules.Procurement.Domain.RfqInvitedVendor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestForQuotationId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_for_quotation_id");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id");

                    b.HasIndex("RequestForQuotationId");

                    b.ToTable("rfq_invited_vendors", "procurement");
                });

            modelBuilder.Entity("Modules.Procurement.Domain.RfqLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("PurchaseRequisitionLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_requisition_line_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RequestForQuotationId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_for_quotation_id");

                    b.HasKey("Id");

                    b.HasIndex("RequestForQuotationId");

                    b.ToTable("rfq_lines", "procurement");
                });

            modelBuilder.Entity("Modules.Procurement.Domain.RfqVendorQuoteLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuotedUnitPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("quoted_unit_price");

                    b.Property<Guid>("RequestForQuotationId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_for_quotation_id");

                    b.Property<Guid>("RfqLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("rfq_line_id");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id");

                    b.HasIndex("RequestForQuotationId");

                    b.ToTable("rfq_vendor_quote_lines", "procurement");
                });

            modelBuilder.Entity("Modules.Procurement.Domain.VendorPrequalification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessPartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_partner_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_number");

                    b.Property<string>("ExtensionFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extension_data");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_type");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Trade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trade");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("vendor_prequalifications", "procurement");
                });

            modelBuilder.Entity("Modules.Procurement.Infrastructure.AttachmentContentRow", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.HasKey("AttachmentId");

                    b.ToTable("attachment_contents", "procurement");
                });

            modelBuilder.Entity("Modules.Procurement.Infrastructure.NumberRangeCounterEntity", b =>
                {
                    b.Property<string>("RangeKey")
                        .HasColumnType("text")
                        .HasColumnName("range_key");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence");

                    b.HasKey("RangeKey", "CompanyId", "FiscalYear");

                    b.ToTable("number_range_counters", "procurement");
                });

            modelBuilder.Entity("Platform.Attachments.AttachmentMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_id");

                    b.Property<string>("BusinessObjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("business_object_type");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("BusinessObjectType", "BusinessObjectId");

                    b.ToTable("attachments", "procurement");
                });

            modelBuilder.Entity("Platform.Workflow.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicableSteps")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("applicable_steps");

                    b.Property<Guid>("BusinessObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_id");

                    b.Property<string>("BusinessObjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("business_object_type");

                    b.Property<int>("CurrentStepIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_step_index");

                    b.Property<DateTimeOffset?>("CurrentStepStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_step_started_at");

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("definition_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("_approvedByStep")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("approved_by_step");

                    b.Property<string>("_history")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("history");

                    b.Property<string>("_requiredApproversByStep")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("required_approvers_by_step");

                    b.HasKey("Id");

                    b.ToTable("workflow_instances", "procurement");
                });

            modelBuilder.Entity("Modules.Procurement.Domain.GrnLine", b =>
                {
                    b.HasOne("Modules.Procurement.Domain.GoodsReceiptNote", null)
                        .WithMany("Lines")
                        .HasForeignKey("GoodsReceiptNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Procurement.Domain.PurchaseOrderLine", b =>
                {
                    b.HasOne("Modules.Procurement.Domain.PurchaseOrder", null)
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Procurement.Domain.PurchaseRequisitionLine", b =>
                {
                    b.HasOne("Modules.Procurement.Domain.PurchaseRequisition", null)
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Procurement.Domain.RfqInvitedVendor", b =>
                {
                    b.HasOne("Modules.Procurement.Domain.RequestForQuotation", null)
                        .WithMany("InvitedVendors")
                        .HasForeignKey("RequestForQuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Procurement.Domain.RfqLine", b =>
                {
                    b.HasOne("Modules.Procurement.Domain.RequestForQuotation", null)
                        .WithMany("Lines")
                        .HasForeignKey("RequestForQuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Procurement.Domain.RfqVendorQuoteLine", b =>
                {
                    b.HasOne("Modules.Procurement.Domain.RequestForQuotation", null)
                        .WithMany("VendorQuoteLines")
                        .HasForeignKey("RequestForQuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Procurement.Infrastructure.AttachmentContentRow", b =>
                {
                    b.HasOne("Platform.Attachments.AttachmentMetadata", null)
                        .WithOne()
                        .HasForeignKey("Modules.Procurement.Infrastructure.AttachmentContentRow", "AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Procurement.Domain.GoodsReceiptNote", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Modules.Procurement.Domain.PurchaseOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Modules.Procurement.Domain.PurchaseRequisition", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Modules.Procurement.Domain.RequestForQuotation", b =>
                {
                    b.Navigation("InvitedVendors");

                    b.Navigation("Lines");

                    b.Navigation("VendorQuoteLines");
                });
#pragma warning restore 612, 618
        }
    }
}
