// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Construction.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Construction.Infrastructure.Migrations
{
    [DbContext(typeof(ConstructionDbContext))]
    [Migration("20260717081556_AddIpcBillingAccounts")]
    partial class AddIpcBillingAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("construction")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Construction.Domain.BackCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("DateIncurred")
                        .HasColumnType("date")
                        .HasColumnName("date_incurred");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("SubcontractId")
                        .HasColumnType("uuid")
                        .HasColumnName("subcontract_id");

                    b.HasKey("Id");

                    b.HasIndex("SubcontractId");

                    b.ToTable("back_charges", "construction");
                });

            modelBuilder.Entity("Modules.Construction.Domain.BoqLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DescriptionArabic")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description_arabic");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("rate");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit_of_measure");

                    b.Property<Guid>("WbsElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("wbs_element_id");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("boq_lines", "construction");
                });

            modelBuilder.Entity("Modules.Construction.Domain.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AdvancePaymentPercentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("advance_payment_percentage");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contract_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<int?>("DefectsLiabilityPeriodMonths")
                        .HasColumnType("integer")
                        .HasColumnName("defects_liability_period_months");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_number");

                    b.Property<string>("ExtensionFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extension_data");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("payment_terms");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("contracts", "construction");
                });

            modelBuilder.Entity("Modules.Construction.Domain.Ipc", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AdvancePaymentPercentageApplied")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("advance_payment_percentage_applied");

                    b.Property<Guid>("CommercialDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("commercial_document_id");

                    b.Property<string>("CommercialDocumentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("commercial_document_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_number");

                    b.Property<string>("ExtensionFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extension_data");

                    b.Property<Guid?>("LinkedArInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_ar_invoice_id");

                    b.Property<Guid>("MeasurementSheetId")
                        .HasColumnType("uuid")
                        .HasColumnName("measurement_sheet_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<decimal>("OtherDeductions")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("other_deductions");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("ReceivableAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("receivable_account_id");

                    b.Property<decimal?>("RetentionPercentageApplied")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("retention_percentage_applied");

                    b.Property<Guid?>("RevenueAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("revenue_account_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TaxCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tax_code_id");

                    b.Property<Guid?>("VatAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("vat_account_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("ipcs", "construction");
                });

            modelBuilder.Entity("Modules.Construction.Domain.IpcLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommercialDocumentLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("commercial_document_line_id");

                    b.Property<Guid>("IpcId")
                        .HasColumnType("uuid")
                        .HasColumnName("ipc_id");

                    b.Property<decimal>("QuantityThisPeriod")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity_this_period");

                    b.Property<decimal>("QuantityToDate")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity_to_date");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("rate");

                    b.HasKey("Id");

                    b.HasIndex("IpcId");

                    b.ToTable("ipc_lines", "construction");
                });

            modelBuilder.Entity("Modules.Construction.Domain.MeasurementLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommercialDocumentLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("commercial_document_line_id");

                    b.Property<Guid>("MeasurementSheetId")
                        .HasColumnType("uuid")
                        .HasColumnName("measurement_sheet_id");

                    b.Property<decimal?>("QuantityCertified")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity_certified");

                    b.Property<decimal>("QuantitySubmitted")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity_submitted");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("remarks");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementSheetId");

                    b.ToTable("measurement_lines", "construction");
                });

            modelBuilder.Entity("Modules.Construction.Domain.MeasurementSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommercialDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("commercial_document_id");

                    b.Property<string>("CommercialDocumentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("commercial_document_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_number");

                    b.Property<string>("ExtensionFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extension_data");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("measurement_sheets", "construction");
                });

            modelBuilder.Entity("Modules.Construction.Domain.Subcontract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<int?>("DefectsLiabilityPeriodMonths")
                        .HasColumnType("integer")
                        .HasColumnName("defects_liability_period_months");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_number");

                    b.Property<string>("ExtensionFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extension_data");

                    b.Property<decimal?>("MobilizationAdvancePercentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("mobilization_advance_percentage");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<decimal?>("RetentionPercentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("retention_percentage");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubcontractorId")
                        .HasColumnType("uuid")
                        .HasColumnName("subcontractor_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("subcontracts", "construction");
                });

            modelBuilder.Entity("Modules.Construction.Domain.SubcontractLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DescriptionArabic")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description_arabic");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("rate");

                    b.Property<Guid>("SubcontractId")
                        .HasColumnType("uuid")
                        .HasColumnName("subcontract_id");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit_of_measure");

                    b.Property<Guid>("WbsElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("wbs_element_id");

                    b.HasKey("Id");

                    b.HasIndex("SubcontractId");

                    b.ToTable("subcontract_lines", "construction");
                });

            modelBuilder.Entity("Modules.Construction.Infrastructure.NumberRangeCounterEntity", b =>
                {
                    b.Property<string>("RangeKey")
                        .HasColumnType("text")
                        .HasColumnName("range_key");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence");

                    b.HasKey("RangeKey", "CompanyId", "FiscalYear");

                    b.ToTable("number_range_counters", "construction");
                });

            modelBuilder.Entity("Platform.Workflow.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicableSteps")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("applicable_steps");

                    b.Property<Guid>("BusinessObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_id");

                    b.Property<string>("BusinessObjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("business_object_type");

                    b.Property<int>("CurrentStepIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_step_index");

                    b.Property<DateTimeOffset?>("CurrentStepStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_step_started_at");

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("definition_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("_approvedByStep")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("approved_by_step");

                    b.Property<string>("_history")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("history");

                    b.Property<string>("_requiredApproversByStep")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("required_approvers_by_step");

                    b.HasKey("Id");

                    b.ToTable("workflow_instances", "construction");
                });

            modelBuilder.Entity("Modules.Construction.Domain.BackCharge", b =>
                {
                    b.HasOne("Modules.Construction.Domain.Subcontract", null)
                        .WithMany("BackCharges")
                        .HasForeignKey("SubcontractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Construction.Domain.BoqLine", b =>
                {
                    b.HasOne("Modules.Construction.Domain.Contract", null)
                        .WithMany("BoqLines")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Construction.Domain.IpcLine", b =>
                {
                    b.HasOne("Modules.Construction.Domain.Ipc", null)
                        .WithMany("Lines")
                        .HasForeignKey("IpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Construction.Domain.MeasurementLine", b =>
                {
                    b.HasOne("Modules.Construction.Domain.MeasurementSheet", null)
                        .WithMany("Lines")
                        .HasForeignKey("MeasurementSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Construction.Domain.SubcontractLine", b =>
                {
                    b.HasOne("Modules.Construction.Domain.Subcontract", null)
                        .WithMany("Lines")
                        .HasForeignKey("SubcontractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Construction.Domain.Contract", b =>
                {
                    b.Navigation("BoqLines");
                });

            modelBuilder.Entity("Modules.Construction.Domain.Ipc", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Modules.Construction.Domain.MeasurementSheet", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Modules.Construction.Domain.Subcontract", b =>
                {
                    b.Navigation("BackCharges");

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
