// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Finance.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Finance.Infrastructure.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    partial class FinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("finance")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Finance.Domain.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_number");

                    b.Property<string>("ExtensionFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extension_data");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modified_by");

                    b.Property<DateOnly>("PostingDate")
                        .HasColumnType("date")
                        .HasColumnName("posting_date");

                    b.Property<Guid?>("ReversalOfEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("reversal_of_entry_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("journal_entries", "finance");
                });

            modelBuilder.Entity("Modules.Finance.Domain.JournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CostCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cost_center_id");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("credit_amount");

                    b.Property<decimal>("DebitAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("debit_amount");

                    b.Property<Guid>("GLAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("gl_account_id");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<string>("LineDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("line_description");

                    b.HasKey("Id");

                    b.HasIndex("JournalEntryId");

                    b.ToTable("journal_lines", "finance");
                });

            modelBuilder.Entity("Modules.Finance.Infrastructure.NumberRangeCounterEntity", b =>
                {
                    b.Property<string>("RangeKey")
                        .HasColumnType("text")
                        .HasColumnName("range_key");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence");

                    b.HasKey("RangeKey", "CompanyId", "FiscalYear");

                    b.ToTable("number_range_counters", "finance");
                });

            modelBuilder.Entity("Platform.Workflow.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicableSteps")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("applicable_steps");

                    b.Property<Guid>("BusinessObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_id");

                    b.Property<string>("BusinessObjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("business_object_type");

                    b.Property<int>("CurrentStepIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_step_index");

                    b.Property<DateTimeOffset?>("CurrentStepStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_step_started_at");

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("definition_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("_approvedByStep")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("approved_by_step");

                    b.Property<string>("_history")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("history");

                    b.Property<string>("_requiredApproversByStep")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("required_approvers_by_step");

                    b.HasKey("Id");

                    b.ToTable("workflow_instances", "finance");
                });

            modelBuilder.Entity("Modules.Finance.Domain.JournalLine", b =>
                {
                    b.HasOne("Modules.Finance.Domain.JournalEntry", null)
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Finance.Domain.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
